services:
  clab:
    image: ghcr.io/srl-labs/clab
    container_name: containerlab
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    # Set the working directory
    working_dir: "$PWD/clab"
    environment:
      CLAB_NORNIR_PLATFORM_NAME_SCHEMA: "napalm"
    # volumes can be mounted from our host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/netns:/var/run/netns
      - /etc/hosts:/etc/hosts
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ${PWD}/clab:${PWD}/clab:rw
    pid: host
    entrypoint: ./entrypoint.sh
    command: bash

  runner:
    build: nornir
    container_name: nornir-runner
    network_mode: host
    restart: unless-stopped
    env_file: nornir/.env
    volumes:
      - /etc/hosts:/etc/hosts:ro
    depends_on:
      clab:
        condition: service_started

# networks:
#   clab:
#     external: true
#     name: clab
