name: Dry Run changes
on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
      - edited

permissions:
  contents: read
  pull-requests: read

jobs:
  Identify-changes:
    runs-on: ["self-hosted"]
    name: test_flow
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: install requirements
        run: |
          pip3 install -r requirements.txt
      - name: Apply service modified filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            crqs:
              - add|modified : change-requests/**

      - name: Run nornir
        if: ${{ steps.filter.outputs.crqs == 'true' }}
        run: |
          python3 configure_prod_devices.py --dry_run